[instance]
problem_instance = "/fjsp/1_Brandimarte/Mk01.fjs"

[algorithm]
population_size = 10 # number of individuals in the population
ngen = 100 # number of generations
rseed = 5 # random seed
indpb = 0.03 # probability of mutating each gene
cr = 0.7 # probability of mating

[output]
logbook = true # display logbook during search
plotting = true # plot instance representation and ganttchart
